export const projects = [
  {
    title: 'Portfolio',
    description: "The very own site you are using right now built to showcase my skills and my projects in a neat way, built using React and Next JS",
      image: '/images/1.jpg',
      tags: ['ReactJS', 'NextJS'],
    source: 'https://github.com/divyanshugupta14/Divyanshu_Portfolio',
    visit: 'https://divyanshu-portfolio.vercel.app/',
    id: 0,
  },
  {
    title: 'Covid Tracker',
    description:"A site for tracking the daily covid cases of each country allowing easy tracking of increase/decrease in cases through chart",
    image: '/images/2.png',
    tags: ['ReactJS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Blog App',
    description:"A site built for blogging, showing all the posts in a neat way Provides functionality to easily add new posts and also edit previous posts",
    image: '/images/3.png',
    tags: ['ReactJS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  // {
  //   title: 'Unichat',
  //   description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
  //   image: '/images/4.jpg',
  //   tags: ['React', 'ChatEngine', 'Firebase'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 3,
  // },
  // {
  //   title: 'MERN Memories',
  //   description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
  //     image: '/images/1.png',
  //     tags: ['Mongo', 'Express', 'React', 'Node'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 3,
  // },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];